



#Author: Eamonn Gaynor

#Date: 08/10/2018

#File: Semaphore.h

#Brief: Makefile to run signal.cpp and Semaphore.cpp

#Bugs: N/A

#Licence: GNU (General Public License)


CC=g++
CFLAGS= -std=c++11 -pthread
FILES= signal.cpp Semaphore.cpp
OUT_EXE=signal

build: $(FILES)
	$(CC) -o $(OUT_EXE) $(FILES) $(CFLAGS)
